# Generated by Django 6.0 on 2026-01-11 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Qurilish ob'ektining nomi", max_length=255, verbose_name='Bino nomi')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('started', 'Qurilish boshlangan'), ('finished', 'Tugatildi')], default='new', help_text='Binoning joriy holati: Yangi, Qurilish boshlangan yoki Tugatildi', max_length=20, verbose_name='Qurilish holati')),
                ('budget', models.DecimalField(decimal_places=2, default=0, help_text="Binoga ajratilgan umumiy mablag' (so'm)", max_digits=15, verbose_name="Ajratilgan mablag'")),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, help_text="Hozirga qadar sarflangan mablag' (so'm)", max_digits=15, verbose_name="Sarflangan mablag'")),
                ('start_date', models.DateField(blank=True, help_text='Qurilish ishlari boshlangan sana', null=True, verbose_name='Qurilish boshlangan sana')),
                ('end_date', models.DateField(blank=True, help_text='Qurilish ishlarining taxminiy tugash sanasi', null=True, verbose_name='Taxminiy tugash sanasi')),
                ('description', models.TextField(blank=True, help_text="Bino haqida qo'shimcha ma'lumot", verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Bino',
                'verbose_name_plural': 'Binolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Material yoki uskuna nomi', max_length=255, verbose_name='Mol-mulk nomi')),
                ('image', models.ImageField(blank=True, help_text='Material yoki uskuna rasmi', null=True, upload_to='assets/', verbose_name='Rasm')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Mol-mulk miqdori', verbose_name='Miqdor')),
                ('unit', models.CharField(blank=True, default='dona', help_text='Masalan: dona, kg, metr, litr', max_length=50, verbose_name="O'lchov birligi")),
                ('payment_status', models.CharField(choices=[('paid', "To'langan"), ('unpaid', "To'lanmagan")], default='unpaid', help_text="Mol-mulk uchun to'lov amalga oshirilganmi", max_length=20, verbose_name="To'lov holati")),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text="Mol-mulkning narxi (so'm)", max_digits=15, verbose_name='Summa')),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha izohlar", verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('building', models.ForeignKey(help_text='Mol-mulk qaysi binoga tegishli', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='main.building', verbose_name='Bino')),
            ],
            options={
                'verbose_name': 'Mol-mulk',
                'verbose_name_plural': 'Mol-mulklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('material', 'Material'), ('labor', 'Ish haqi'), ('transport', 'Transport'), ('equipment', 'Uskuna'), ('other', 'Boshqa')], default='other', help_text='Chiqim turi', max_length=20, verbose_name='Kategoriya')),
                ('description', models.CharField(help_text="Chiqim haqida qisqacha ma'lumot", max_length=500, verbose_name='Tavsif')),
                ('amount', models.DecimalField(decimal_places=2, help_text="Chiqim summasi (so'm)", max_digits=15, verbose_name='Summa')),
                ('date', models.DateField(help_text='Chiqim amalga oshirilgan sana', verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('asset', models.ForeignKey(blank=True, help_text='Chiqim qaysi mol-mulkka tegishli (ixtiyoriy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='main.asset', verbose_name='Mol-mulk')),
                ('building', models.ForeignKey(help_text='Chiqim qaysi binoga tegishli', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main.building', verbose_name='Bino')),
                ('created_by', models.ForeignKey(help_text="Chiqimni kim qo'shgan", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqimlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
