# Generated by Django 6.0 on 2026-01-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='asset',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
