# Generated by Django 6.0 on 2026-01-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_expense_asset_delete_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/', verbose_name='Rasm'),
        ),
    ]
