# Generated by Django 6.0 on 2026-01-13 07:45

import django.db.models.deletion
from django.db import migrations, models


def populate_categories_and_migrate_data(apps, schema_editor):
    """Ma'lumotlarni ko'chirish: eski category -> ExpenseCategory -> yangi FK"""
    ExpenseCategory = apps.get_model('main', 'ExpenseCategory')
    Expense = apps.get_model('main', 'Expense')
    
    # Standart kategoriyalarni yaratish
    categories_data = [
        {'slug': 'material', 'name': 'Materiallar', 'icon': 'Package', 'color': 'text-amber-400 bg-amber-500/20 border-amber-500/30', 'order': 1},
        {'slug': 'labor', 'name': 'Ish haqi', 'icon': 'Users', 'color': 'text-blue-400 bg-blue-500/20 border-blue-500/30', 'order': 2},
        {'slug': 'transport', 'name': 'Transport', 'icon': 'Truck', 'color': 'text-purple-400 bg-purple-500/20 border-purple-500/30', 'order': 3},
        {'slug': 'equipment', 'name': 'Uskunalar', 'icon': 'Wrench', 'color': 'text-emerald-400 bg-emerald-500/20 border-emerald-500/30', 'order': 4},
        {'slug': 'other', 'name': 'Boshqa', 'icon': 'MoreHorizontal', 'color': 'text-slate-400 bg-slate-500/20 border-slate-500/30', 'order': 5},
    ]
    
    category_map = {}
    for cat_data in categories_data:
        cat, _ = ExpenseCategory.objects.get_or_create(
            slug=cat_data['slug'],
            defaults=cat_data
        )
        category_map[cat_data['slug']] = cat
    
    # Mavjud chiqimlarni yangilash
    for expense in Expense.objects.all():
        old_cat = expense.legacy_category or 'other'
        if old_cat in category_map:
            expense.category = category_map[old_cat]
            expense.save(update_fields=['category'])


def reverse_migrate_data(apps, schema_editor):
    """Reverse: FK -> eski string"""
    Expense = apps.get_model('main', 'Expense')
    for expense in Expense.objects.select_related('category').all():
        if expense.category:
            expense.legacy_category = expense.category.slug
            expense.save(update_fields=['legacy_category'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_expense_image'),
    ]

    operations = [
        # 1. ExpenseCategory modelini yaratish
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kategoriya nomi (masalan: Materiallar, Ish haqi)', max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(help_text='URL-friendly identifikator (masalan: material, labor)', unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, default='', help_text='Lucide icon nomi (masalan: Package, Users)', max_length=50, verbose_name='Icon nomi')),
                ('color', models.CharField(blank=True, default='text-slate-400 bg-slate-500/20 border-slate-500/30', help_text='Tailwind CSS rang klasslari', max_length=100, verbose_name='Rang klassi')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ko'rsatish tartibi (kichik raqam birinchi)", verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, help_text="Kategoriya faol holatda (tanlash uchun ko'rinadi)", verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Chiqim kategoriyasi',
                'verbose_name_plural': 'Chiqim kategoriyalari',
                'ordering': ['order', 'name'],
            },
        ),
        
        # 2. Eski category ni legacy_category ga nusxalash uchun yangi maydon
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='legacy_category',
        ),
        
        # 3. Yangi FK category maydonini qo'shish (null=True)
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='expenses', 
                to='main.expensecategory', 
                verbose_name='Kategoriya'
            ),
        ),
        
        # 4. Ma'lumotlarni ko'chirish
        migrations.RunPython(
            populate_categories_and_migrate_data,
            reverse_migrate_data
        ),
    ]
