# Generated by Django 6.0 on 2026-01-13 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_expense_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Chiqim turi', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='main.expensecategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Chiqim amalga oshirilgan sana', verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='legacy_category',
            field=models.CharField(blank=True, choices=[('material', 'Material'), ('labor', 'Ish haqi'), ('transport', 'Transport'), ('equipment', 'Uskuna'), ('other', 'Boshqa')], default='other', help_text='Eski kategoriya (migration uchun)', max_length=20, verbose_name='Eski kategoriya'),
        ),
    ]
